### ISSUE TITLE
Display bugs and requests

### ISSUE THREAD

**Issue by YGrumeau** [exmachina-dev/ABK-firmware#1]
- **DISPLAY BUG**: On small screens, impossible to access bottom configuration.
![2017-12-12 11_33_26-](https://user-images.githubusercontent.com/34475347/33880770-fae9ed0a-df32-11e7-848c-6ca4ad4a8466.png)

- **REQUESTS**: 
**1)** Define maximum surface as 100 m2. Also, define new case with fabric's weight (xxx g/m2) and calculate weight, make alert if weight > 15 kg.
![2017-12-12 11_35_24-abk configuration tool](https://user-images.githubusercontent.com/34475347/33880780-01ac32a6-df33-11e7-90da-3056a687a5f5.png)

**2)** Define maximum speed at 7.5m/s and maximum acceleration.
![2017-12-12 11_35_56-abk configuration tool](https://user-images.githubusercontent.com/34475347/33880801-175e9828-df33-11e7-8312-5bd9421cd5fe.png)

**3)** Speed 7.5 m/s is 100% and not 75%
![2017-12-12 11_36_41-abk configuration tool](https://user-images.githubusercontent.com/34475347/33880828-2d8d7a38-df33-11e7-827a-b540bb7eeb96.png)

**4)** Does the "Points" window must be something configurable ? Can't it be greyed values dependent of what is entered in the "Wizard" window?
![2017-12-12 11_39_43-abk configuration tool](https://user-images.githubusercontent.com/34475347/33880843-32d5f074-df33-11e7-9efc-8b8bf6ed25df.png)

**Comment by WillyKaze** [comment]
This issue is now split into #2, #3, #4, #5, #6 and #7.
