### ISSUE TITLE
Maximum speed limit and acceleration

### ISSUE THREAD

**Issue by YGrumeau** [exmachina-dev/ABK-firmware#5]
From #1 

Define maximum speed at 7.5 m/s and maximum acceleration 7.5m/s2.

![2017-12-12 11_35_56-abk configuration tool](https://user-images.githubusercontent.com/34475347/33892081-2b21c4fa-df58-11e7-8069-3f8acc29325c.png)

**Comment by WillyKaze** [comment]
> maximum speed at 7.5 m/s

This is already configurable in `File > Options`
We need to all the limits in this spin box.

> maximum acceleration 7.5m/s2

Has to be implemented.
