### ISSUE TITLE
"Points" window

### ISSUE THREAD

**Issue by YGrumeau** [exmachina-dev/ABK-firmware#7]
Shouldn't it be greyed with no entries possible (all entries possible in "wizard" window only…)?

![2017-12-12 11_39_43-abk configuration tool](https://user-images.githubusercontent.com/34475347/33892735-d4c72080-df59-11e7-8609-6081ff1ed4f4.png)

**Comment by WillyKaze** [comment]
This tab is active because the wizard helps setting default values. However, customization might be needed depending the onsite configuration.

Could be possible to have those enable with an `Advanced mode`. Is it really necessary ?
